name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
#Test
    - uses: Azure/docker-login@v1
      with:
        login-server: vsazurecr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t VSGHE-aspdotnet .
        docker tag VSGHE-aspdotnet vsazurecr.azurecr.io/vsaspdotnet:v1.1
        docker push vsazurecr.azurecr.io/vsaspdotnet:v1.1
  #    docker build . -t vsazurecr.azurecr.io/vsdotnetapp:1.0.0
  #    docker push vsazurecr.azurecr.io/vsdotnetapp:1.0.0
  #    docker build . -t samplegroupacr.azurecr.io/csharp:1.2.2
              
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: VSGHE
        resource-group: VSGHE
        
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: vsgheacr.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: demo-vsdotnetapp-secret

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
            vsazurecr.azurecr.io/vsaspdotnet:v1.1
            #      vsazurecr.azurecr.io/vsdotnetapp:${{ github.sha }}
        imagepullsecrets: |
          demo-vsdotnetapp-secret
